# Generated by Django 3.1.3 on 2020-12-11 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kisiler',
            fields=[
                ('kisi_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Kişi No')),
                ('adi_soyadi', models.TextField(verbose_name='Ad Soyad')),
                ('tckimlik', models.BigIntegerField(unique=True, verbose_name='TC Kimlik')),
                ('tel', models.IntegerField(verbose_name='Telefon')),
                ('foto', models.TextField()),
                ('kisi_tipi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Girisler',
            fields=[
                ('giris_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Giriş No')),
                ('tarih', models.DateTimeField(verbose_name='Tarih')),
                ('saat', models.DateTimeField(verbose_name='Saat')),
                ('v_isi', models.FloatField(verbose_name='Vücut ısısı')),
                ('kisi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icerik.kisiler')),
            ],
        ),
    ]
