# Generated by Django 3.1.3 on 2020-12-11 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giris_iptal',
            fields=[
                ('giris_iptal_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Giriş No')),
                ('tarih', models.DateTimeField(verbose_name='Tarih')),
                ('v_isi', models.FloatField(verbose_name='Vücut ısısı')),
                ('kisi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icerik.kisiler')),
            ],
        ),
    ]
