# Generated by Django 3.1.3 on 2020-12-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0002_giris_iptal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giris_iptal',
            name='tarih',
            field=models.DateField(verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='girisler',
            name='saat',
            field=models.TimeField(verbose_name='Saat'),
        ),
        migrations.AlterField(
            model_name='girisler',
            name='tarih',
            field=models.DateField(verbose_name='Tarih'),
        ),
    ]
