# Generated by Django 3.1.3 on 2020-12-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0003_auto_20201212_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giris_iptal',
            old_name='kisi_id',
            new_name='kisi',
        ),
        migrations.RenameField(
            model_name='girisler',
            old_name='kisi_id',
            new_name='kisi',
        ),
    ]
